MOD_HEADERS := image_t.h image_t_remote.h image_t_local.h image_t_mbtiles.h
MOD_SOURCES := image_t.cpp image_t_remote.cpp image_t_local.cpp image_t_mbtiles.cpp
SIMPLE_TESTS := image_t image_t_mbtiles

PKG_CONFIG = sqlite3

include ../Makefile.inc
