MOD_HEADERS := mapview.h css.h\
               dlg_err.h dlg_confirm.h dlg_show_pt.h dlg_trk_opt.h\
               panel_status.h panel.h\
               panel_wpts.h panel_trks.h panel_maps.h\
               panel_mapdb.h\
               action_manager.h action_mode.h\
               am_file.h am_view.h am_panel.h am_trks.h am_maps.h am_mapdb.h am_srtm.h\
               w_rainbow.h w_simple_combo.h w_comboboxes.h w_coord_box.h\
               w_nom_box.h w_page_box.h

MOD_SOURCES := mapview.cpp css.cpp\
               dlg_err.cpp dlg_confirm.cpp dlg_show_pt.cpp dlg_trk_opt.cpp\
               panel_wpts.cpp panel_trks.cpp panel_maps.cpp\
               action_manager.cpp\
               w_rainbow.cpp w_comboboxes.cpp w_coord_box.cpp\
               w_nom_box.cpp w_page_box.cpp

PKG_CONFIG := gtkmm-3.0

include ../Makefile.inc
