MOD_HEADERS := mapview.h\
               dlg_err.h dlg_chconf.h\
               panel_status.h panel.h\
               panel_wpts.h panel_trks.h panel_maps.h\
               panel_mapdb.h\
               action_manager.h action_mode.h\
               am_file.h am_view.h am_panel.h am_maps.h am_mapdb.h\
               w_rainbow.h w_simple_combo.h w_comboboxes.h

MOD_SOURCES := mapview.cpp\
               dlg_err.cpp dlg_chconf.cpp\
               panel_wpts.cpp panel_trks.cpp panel_maps.cpp\
               action_manager.cpp\
               w_rainbow.cpp w_comboboxes.cpp

PKG_CONFIG := gtkmm-3.0

include ../Makefile.inc
