MOD_HEADERS  := point.h line.h multiline.h rect.h line_walker.h poly_tools.h poly_op.h point_int.h line_rectcrop.h
MOD_SOURCES  := json_pt.cpp line_walker.cpp point_int.cpp line_rectcrop.cpp
SIMPLE_TESTS := point line multiline rect line_walker poly_tools poly_op point_int
PKG_CONFIG   := jansson

include ../Makefile.inc
