MOD_HEADERS := ocad_colors.h ocad_file.h ocad_geo.h ocad_index.h\
               ocad_object8.h ocad_object9.h ocad_object.h ocad_string.h\
               ocad_symbol8.h ocad_symbol9.h ocad_symbol.h ocad_types.h

MOD_SOURCES := ocad_colors.cpp ocad_file.cpp ocad_geo.cpp\
               ocad_object8.cpp ocad_object9.cpp ocad_object.cpp\
               ocad_string.cpp ocad_symbol8.cpp ocad_symbol9.cpp ocad_symbol.cpp\
               ocad_types.cpp



PROGRAMS := ocad2ocad

include ../Makefile.inc
