MOD_HEADERS := vmap2obj.h vmap2.h\
               db_tools.h db_simple.h db_geohash.h string_pack.h\
               vmap2types.h


MOD_SOURCES := vmap2obj.cpp vmap2.cpp\
               db_tools.cpp db_simple.cpp db_geohash.cpp string_pack.cpp\
               vmap2types.cpp

SIMPLE_TESTS := vmap2obj vmap2\
                db_simple db_geohash string_pack

PKG_CONFIG = 'libdb'
CXXFLAGS = -g

#PROGRAMS = ms2mapdb

include ../Makefile.inc
