MOD_HEADERS := vmap2obj.h vmap2.h vmap2io.h\
               db_tools.h db_simple.h db_geohash.h string_pack.h\
               vmap2types.h vmap2gobj.h vmap2tools.h


MOD_SOURCES := vmap2obj.cpp vmap2.cpp vmap2io.cpp\
               vmap2io_vmap.cpp vmap2io_mp.cpp vmap2io_fig.cpp vmap2io_osm.cpp\
               db_tools.cpp db_simple.cpp db_geohash.cpp string_pack.cpp\
               vmap2types.cpp vmap2gobj.cpp vmap2tools.cpp

SIMPLE_TESTS := vmap2obj vmap2\
                db_simple db_geohash string_pack

PKG_CONFIG = 'libdb'
CXXFLAGS = -g

include ../Makefile.inc
