#!/bin/sh -efu

prog=${1:-./read_words.test}

assert(){
  res="$1"
  exp="$2"
  if [ "$res" != "$exp" ]; then
    printf "ERROR:\n"
    printf "  exp:  %s\n" "$exp"
    printf "  res:  %s\n" "$res"
    return 1
  fi
  return 0
}

assert "$(cat test_data/read_words1 | "$prog")" \
"$(cat <<EOF
1-1: [a] [#] [ABc] [aBC] [ a' s ]
2-2: [d] [e] [f] [ a' s]
3-3: [\]
6-7: [ab
c] [de	f]
8-9: [abc] [def]
10-10: [aa] [bb] [cc""dd''ee] [] [] ['']
EOF
)"

assert "$(cat test_data/read_words1 | "$prog" -r)" \
"$(cat test_data/read_words1r)"

# same with lowercase option
assert "$(cat test_data/read_words1 | "$prog" -l)" \
"$(cat <<EOF
1-1: [a] [#] [abc] [abc] [ a' s ]
2-2: [d] [e] [f] [ a' s]
3-3: [\]
6-7: [ab
c] [de	f]
8-9: [abc] [def]
10-10: [aa] [bb] [cc""dd''ee] [] [] ['']
EOF
)"

assert "$(cat test_data/read_words1 | "$prog" -r -l)" \
"$(cat test_data/read_words1r)"


assert "$(cat test_data/read_words2 | "$prog")" \
"$(cat <<EOF
1-1: [a] [b "C" d] [e e]
2-2: [a] [b 'C' d] [e	e]
3-6: [a
b
c
]
7-9: [a
b
c]
EOF
)"

assert "$(cat test_data/read_words2 | "$prog" -r)" \
"$(cat test_data/read_words2r)"

assert "$(cat test_data/read_words3 | "$prog")" \
"$(cat <<EOF
5-5: [a
]
6-6: [a
]
7-7: [a
]
10-10: [a
9]
12-12: [a1
9]
21-21: [
]
EOF
)"

assert "$(cat test_data/read_words3 | "$prog" -r)" \
"$(cat test_data/read_words3r)"

assert "$(cat test_data/read_words4 | "$prog")" \
"1-1: [define] [w1] [123]
2-2: [use] [123]"


assert "$(echo abcdez | "$prog")" "1-1: [abcdez]"
assert "$(echo ABCDEZ | "$prog")" "1-1: [ABCDEZ]"

assert "$(echo abcdez | "$prog" -l)" "1-1: [abcdez]"
assert "$(echo ABCDEZ | "$prog" -l)" "1-1: [abcdez]"

assert "$(echo абвгдеёжзийклмнопрстуфхцчшщъыьэюя | "$prog")" "1-1: [абвгдеёжзийклмнопрстуфхцчшщъыьэюя]"
assert "$(echo АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ | "$prog")" "1-1: [АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ]"

assert "$(echo абвгдеёжзийклмнопрстуфхцчшщъыьэюя | "$prog" -l)" "1-1: [абвгдеёжзийклмнопрстуфхцчшщъыьэюя]"
assert "$(echo АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ | "$prog" -l)" "1-1: [АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ]"

assert "$(printf "#a\n\n\"b\n\nc" | "$prog" 2>&1)" \
"Error: Unclosed quote in line 4"

