MOD_HEADERS := image_cnt.h image_trace.h
MOD_SOURCES := image_cnt.cpp image_trace.cpp
PROGRAMS := image_cnt.test1 image_cnt.test2\
            image_trace_river.test image_trace_map.test

include ../Makefile.inc
