MOD_HEADERS := db_tools.h db_geohash.h db_simple.h\
               mapdb.h mapdb_obj.h gobj_mapdb.h conv_label.h
MOD_SOURCES := db_tools.cpp db_geohash.cpp db_simple.cpp string_pack.cpp\
               mapdb.cpp mapdb_obj.cpp mapdb_vmap.cpp mapdb_mp.cpp gobj_mapdb.cpp conv_label.cpp

SIMPLE_TESTS := db_geohash db_geohash_mem db_simple string_pack\
                mapdb mapdb_obj
PKG_CONFIG = 'libdb'
CXXFLAGS = -g

include ../Makefile.inc
