MOD_HEADERS := mapdb.h mapdb_types.h\
               mapdb_storage_io.h\
               gobj_mapdb.h conv_label.h\


MOD_SOURCES := mapdb.cpp mapdb_types.cpp\
               mapdb_storage_io.cpp\
               gobj_mapdb.cpp conv_label.cpp\

#               mapdb_vmap.cpp mapdb_mp.cpp\


#SIMPLE_TESTS :=
CXXFLAGS = -g

PROGRAMS = ms2mapdb

include ../Makefile.inc
