MOD_HEADERS := gobj_trk.h gobj_wpts.h gobj_maps.h\
               gobj_srtm.h\
               draw_pulk_grid.h write_geoimg.h

MOD_SOURCES := gobj_trk.cpp gobj_wpts.cpp gobj_maps.cpp\
               gobj_srtm.cpp\
               draw_pulk_grid.cpp write_geoimg.cpp

PROGRAMS := gobj_srtm.example

include ../Makefile.inc
