MOD_HEADERS := gobj_trk.h gobj_wpts.h gobj_maps.h\
               gobj_srtm.h gobj_pano.h\
               draw_grid.h write_geoimg.h

MOD_SOURCES := gobj_trk.cpp gobj_wpts.cpp gobj_maps.cpp\
               gobj_srtm.cpp gobj_pano.cpp\
               draw_grid.cpp write_geoimg.cpp

SIMPLE_TESTS := gobj_trk gobj_wpts

PROGRAMS := gobj_srtm.example

include ../Makefile.inc
