MOD_HEADERS := colors.h image.h image_r.h image_colors.h\
               io_gif.h io_jpeg.h io_png.h io_tiff.h\
               image_io.h image_cache.h

MOD_SOURCES := colors.cpp image_r.cpp image_colors.cpp\
               io_gif.cpp io_jpeg.cpp io_png.cpp io_tiff.cpp\
               image_io.cpp

SIMPLE_TESTS := colors image_r image_colors\
                io_gif io_jpeg io_png io_tiff\
                image_reduce image_io image_cache

PKG_CONFIG := libgif libjpeg libpng libtiff-4

include ../Makefile.inc
